version: '2'

services:

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  chatuserservice-node:
    image: chatuserservice:latest
    ports:
      - "8081:8081"